added filter by path and tag to unaired and nextaired methods
marcelveldt/script.skin.helper.widgets pull request #21
Opened 2017-09-22 13:03 UTC by redglory

Following the change in next episodes which can be filtered by path and tag parameters, I've applied same concept to nextairing and unaired episodes, which relie on the script.module.tvdb module.

2017-09-24 18:36 UTC, marcelveldt requested changes
thanks for the PR, please see my comments in both PR's (also in tvdb module) before I can accept the merge

2017-09-24 18:36 UTC, marcelveldt commented on resources/lib/episodes.py
> +        episodes = self.metadatautils.thetvdb.get_kodi_unaired_episodes(True, tvshows_ids)
please change this line in 

episodes = self.metadatautils.thetvdb.get_kodi_unaired_episodes(True, False, tvshows_ids)

see my comments in the PR for tvdb module

2017-09-24 18:36 UTC, marcelveldt commented on resources/lib/episodes.py
> +        episodes = self.metadatautils.thetvdb.get_kodi_unaired_episodes(False, tvshows_ids)[:self.options["limit"]]
please change this line in

episodes = self.metadatautils.thetvdb.get_kodi_unaired_episodes(False, False, tvshows_ids)
episodes = episodes[:self.options["limit"]]

see my comments in the PR for tvdb module

2017-10-01 12:01 UTC, redglory commented
You are right!

Fixed thetvdb tvshows_ids parameter and made it optional.

2017-10-02 05:22 UTC, marcelveldt commented
Thanks !

2017-10-02 05:22 UTC, merged